spring.application.name=vcount
# --- SERVER SETUP ---
server.port=8080

# --- DATABASE CONNECTION ---
spring.datasource.url=jdbc:${MYSQL_URL:mysql://localhost:3306/counter_db}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:smartBAS12/}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
